# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

#Set this to "auto" to have gcc determine optimal number of cores (GCC 10+)
NTHREADS="auto"

source /etc/portage/make.conf.lto

CFLAGS="${CFLAGS} -pipe"
CXXFLAGS="${CFLAGS}"
#FCFLAGS="${CFLAGS}"
#FFLAGS="${CFLAGS}"
# WARNING: Changing your CHOST is not something that should be done lightly.
# Please consult https://wiki.gentoo.org/wiki/Changing_the_CHOST_variable before changing.
CHOST="x86_64-pc-linux-gnu"
# These are the USE and USE_EXPAND flags that were used for
# building in addition to what is provided by the profile.
USE="-X bindist -consolekit -introspection -libressl -pulseaudio -qt3support -qt4 -qt5 -xscreensaver alsa icu"
PORTDIR=/var/db/repos/gentoo
DISTDIR=/var/cache/distfiles
PKGDIR=/var/cache/binpkgs
ACCEPT_KEYWORDS="~amd64"
# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C

#rsync_exclude
PORTAGE_RSYNC_EXTRA_OPTS="--exclude-from=/etc/portage/rsync_excludes"

#bindist
#FEATURES="buildpkg"
FEATURES="getbinpkg"
PORTAGE_BINHOST="http://gentooplayers.com/binpkg/x86e/"
