# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
#CFLAGS="-O2 -pipe"
#CFLAGS="-march=armv8-a+crc -mtune=cortex-a53 -ftree-vectorize -O2 -pipe -fomit-frame-pointer"
#Set this to "auto" to have gcc determine optimal number of cores (GCC 10+)
NTHREADS="auto"

source /etc/portage/make.conf.lto

CFLAGS="-march=armv8-a+crc+simd -mtune=cortex-a72 -ftree-vectorize ${CFLAGS} -pipe -fomit-frame-pointer"
CXXFLAGS="${CFLAGS}"

# WARNING: Changing your CHOST is not something that should be done lightly.
# Please consult https://wiki.gentoo.org/wiki/Changing_the_CHOST_variable before changing.
CHOST="aarch64-unknown-linux-gnu"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR=/var/db/repos/gentoo
DISTDIR=/var/cache/distfiles
PKGDIR=/var/cache/binpkgs
# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
ACCEPT_KEYWORDS="~arm64"
MAKEOPTS="-j4"
CPU_FLAGS_ARM="edsp neon thumb vfp vfpv3 vfpv4 vfp-d32 crc32 v4 v5 v6 v7 v8 thumb2"
USE="alsa icu -consolekit -libressl bindist -qt3support -qt4 -qt5 -X -introspection -pulseaudio -xscreensaver"

#python
#PYTHON_TARGETS="python2_7 python3_7"
#PYTHON_SINGLE_TARGET="python3_7"
PORTAGE_RSYNC_EXTRA_OPTS="--exclude-from=/etc/portage/rsync_excludes"

#bindist
#FEATURES="buildpkg"
#FEATURES="getbinpkg"
#PORTAGE_BINHOST="http://gentooplayers.com/binpkg/rpi4/"
